#!/bin/bash

echo HELLOOOOOOOOOOO!!!
echo HELLOOOOOOOOOOO!!!
echo HELLOOOOOOOOOOO!!!
echo HELLOOOOOOOOOOO!!!
echo HELLOOOOOOOOOOO!!!
echo HELLOOOOOOOOOOO!!!
echo HELLOOOOOOOOOOO!!!
echo HELLOOOOOOOOOOO!!!
echo HELLOOOOOOOOOOO!!!
echo HELLOOOOOOOOOOO!!!
echo HELLOOOOOOOOOOO!!!
echo HELLOOOOOOOOOOO!!!
echo HELLOOOOOOOOOOO!!!
echo HELLOOOOOOOOOOO!!!